#!/usr/bin/env python3
"""
pointcloud_metrics.py

Compute Chamfer distance, Hausdorff distance, Precision, Recall (Completeness) and F-score
between pairs of PLY point clouds (geometry + optional color).

Usage (example):
    pip install numpy scipy plyfile
    python pointcloud_metrics.py \
        --gt_dir GrandChallenge/Data/high_quality \
        --rec_dir GrandChallenge/Data/low_quality \
        --out_csv results.csv \
        --threshold 0.5

Optional: include color in distances by specifying --color_weight > 0.
This will append RGB (normalized to [0,1]) multiplied by color_weight to the XYZ coordinates
so that nearest-neighbor distances consider color differences as extra dimensions.

Author: generated by ChatGPT
"""

import os
import argparse
import numpy as np
from plyfile import PlyData
from scipy.spatial import cKDTree
import csv
import sys
import warnings
import re


def read_ply_points(filepath):
    """Read PLY file and return (N,3) points and (N,3) colors or None.
    Handles common PLY color attribute names.
    """
    ply = PlyData.read(filepath)
    # Access vertex element directly (we don't require an explicit existence check)
    v = ply['vertex'].data
    # get x,y,z
    def _get_attr(arr, names):
        for n in names:
            if n in arr.dtype.names:
                return arr[n]
        return None

    xs = _get_attr(v, ('x','X'))
    ys = _get_attr(v, ('y','Y'))
    zs = _get_attr(v, ('z','Z'))
    if xs is None or ys is None or zs is None:
        raise ValueError(f"PLY vertex missing x/y/z in {filepath}")
    points = np.vstack([xs, ys, zs]).T.astype(np.float64)

    # colors: try common names
    rs = _get_attr(v, ('red','r','R','Red'))
    gs = _get_attr(v, ('green','g','G','Green'))
    bs = _get_attr(v, ('blue','b','B','Blue'))
    if rs is None or gs is None or bs is None:
        # some PLYs store color as uint8 in 'colors' or 'rgb' packed
        rgb = _get_attr(v, ('rgb','RGB','rgba','RGBA'))
        if rgb is not None:
            # rgb may be single int per vertex (packed)
            try:
                arr = np.asarray(rgb)
                # if packed as single uint32, unpack
                if arr.dtype.kind in ('i','u') and arr.ndim == 1:
                    vals = arr.astype(np.uint32)
                    r = (vals & 0x0000FF).astype(np.uint8)
                    g = ((vals & 0x00FF00) >> 8).astype(np.uint8)
                    b = ((vals & 0xFF0000) >> 16).astype(np.uint8)
                    colors = np.vstack([r,g,b]).T.astype(np.float32)
                else:
                    colors = np.asarray(rgb).astype(np.float32)
            except Exception:
                colors = None
        else:
            colors = None
    else:
        colors = np.vstack([rs,gs,bs]).T.astype(np.float32)

    # normalize colors to [0,1] if dtype suggests 0-255
    if colors is not None:
        if colors.dtype.kind in ('u','i'):
            maxv = colors.max()
            if maxv > 1:
                colors = colors.astype(np.float32) / 255.0
            else:
                colors = colors.astype(np.float32)
        else:
            # float dtype: assume in [0,1]
            colors = colors.astype(np.float32)

    return points, colors


def build_feature_points(points, colors=None, color_weight=0.0):
    """Return feature points used for NN queries.
    If color_weight>0 and colors provided, concatenate scaled colors.
    """
    if color_weight is None or color_weight <= 0 or colors is None:
        return points
    # ensure same length
    if len(colors) != len(points):
        raise ValueError("colors length != points length")
    cols = colors.astype(np.float64)
    # concatenate XYZ with scaled RGB
    feat = np.hstack([points, cols * float(color_weight)])
    return feat


def chamfer_distance(a_pts, b_pts):
    """Compute symmetric Chamfer distance (mean nearest-neighbor distance).
    Returns (cd_ab, cd_ba, chamfer) where chamfer = 0.5*(mean(d_a->b)+mean(d_b->a))
    """
    tree_b = cKDTree(b_pts)
    d_a_b, _ = tree_b.query(a_pts, k=1)
    tree_a = cKDTree(a_pts)
    d_b_a, _ = tree_a.query(b_pts, k=1)
    mean_ab = np.mean(d_a_b)
    mean_ba = np.mean(d_b_a)
    chamfer = 0.5 * (mean_ab + mean_ba)
    return mean_ab, mean_ba, chamfer


def hausdorff_distance(a_pts, b_pts):
    """Compute symmetric Hausdorff distance (max of one-sided max distances).
    Returns (max_a_to_b, max_b_to_a, hausdorff)
    """
    tree_b = cKDTree(b_pts)
    d_a_b, _ = tree_b.query(a_pts, k=1)
    tree_a = cKDTree(a_pts)
    d_b_a, _ = tree_a.query(b_pts, k=1)
    max_ab = np.max(d_a_b) if len(d_a_b)>0 else 0.0
    max_ba = np.max(d_b_a) if len(d_b_a)>0 else 0.0
    hausdorff = max(max_ab, max_ba)
    return max_ab, max_ba, hausdorff


def precision_recall_fscore(a_pts, b_pts, threshold=0.5):
    """Compute precision, recall (completeness) and fscore at given threshold.
    Define: a_pts = ground-truth P, b_pts = reconstruction Q.
    Precision = fraction of Q points within threshold of P.
    Recall = fraction of P points within threshold of Q.
    """
    tree_a = cKDTree(a_pts)
    d_q_p, _ = tree_a.query(b_pts, k=1)
    precision = np.mean(d_q_p <= threshold) if len(d_q_p)>0 else 0.0

    tree_b = cKDTree(b_pts)
    d_p_q, _ = tree_b.query(a_pts, k=1)
    recall = np.mean(d_p_q <= threshold) if len(d_p_q)>0 else 0.0

    if precision + recall == 0:
        fscore = 0.0
    else:
        fscore = 2 * (precision * recall) / (precision + recall)
    return precision, recall, fscore, np.mean(d_q_p), np.mean(d_p_q)


def find_matching_pairs(gt_dir, rec_dir):
    """Match files by frame (last 4 digits of basename). Return list of (gt_path, rec_path, gt_basename).
    If a file doesn't end with 4 digits, the full basename is used as the key.
    """
    frame_re = re.compile(r"(\d{4})$")

    def build_map(d):
        m = {}
        for f in os.listdir(d):
            if not f.lower().endswith('.ply'):
                continue
            base = os.path.splitext(f)[0]
            mm = frame_re.search(base)
            key = mm.group(1) if mm else base
            # keep full path
            m[key] = os.path.join(d, f)
        return m

    gt_map = build_map(gt_dir)
    rec_map = build_map(rec_dir)

    common_keys = sorted(set(gt_map.keys()) & set(rec_map.keys()))
    pairs = [(gt_map[k], rec_map[k], os.path.splitext(os.path.basename(gt_map[k]))[0]) for k in common_keys]
    missing_in_rec = sorted(set(gt_map.keys()) - set(rec_map.keys()))
    missing_in_gt = sorted(set(rec_map.keys()) - set(gt_map.keys()))
    return pairs, missing_in_rec, missing_in_gt


def process_all(gt_dir, rec_dir, out_csv, threshold=0.5, color_weight=0.0, verbose=True, append=False, max_points=0):
    pairs, missing_in_rec, missing_in_gt = find_matching_pairs(gt_dir, rec_dir)
    if verbose:
        print(f"Found {len(pairs)} matching PLY pairs. {len(missing_in_rec)} missing in rec, {len(missing_in_gt)} missing in gt.")
        if missing_in_rec:
            print("Warning: files in GT missing in REC:", missing_in_rec[:5])
        if missing_in_gt:
            print("Warning: files in REC missing in GT:", missing_in_gt[:5])

    fieldnames = [
        'name', 'frame', 'gt_path', 'rec_path',
        'mean_d_gt_to_rec', 'mean_d_rec_to_gt', 'chamfer',
        'max_d_gt_to_rec', 'max_d_rec_to_gt', 'hausdorff',
        'precision', 'recall', 'fscore',
        'mean_rec_to_gt', 'mean_gt_to_rec'
    ]

    mode = 'a' if append else 'w'
    write_header = True
    if append and os.path.exists(out_csv):
        # if appending to an existing file, don't re-write header
        write_header = False

    with open(out_csv, mode, newline='') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        if write_header:
            writer.writeheader()

        for gt_path, rec_path, name in pairs:
            if verbose:
                print(f"Processing: {name}")
            try:
                gt_pts, gt_colors = read_ply_points(gt_path)
            except Exception as e:
                warnings.warn(f"Failed to read GT {gt_path}: {e}")
                continue
            try:
                rec_pts, rec_colors = read_ply_points(rec_path)
            except Exception as e:
                warnings.warn(f"Failed to read REC {rec_path}: {e}")
                continue

            # optionally subsample points to speed up NN queries
            if max_points and max_points > 0:
                # reproducible sampling
                rng = np.random.default_rng(0)
                if len(gt_pts) > max_points:
                    idx = rng.choice(len(gt_pts), size=max_points, replace=False)
                    gt_pts = gt_pts[idx]
                    if gt_colors is not None and len(gt_colors) == len(idx):
                        gt_colors = gt_colors[idx]
                if len(rec_pts) > max_points:
                    idx = rng.choice(len(rec_pts), size=max_points, replace=False)
                    rec_pts = rec_pts[idx]
                    if rec_colors is not None and len(rec_colors) == len(idx):
                        rec_colors = rec_colors[idx]

            # build features
            gt_feat = build_feature_points(gt_pts, gt_colors, color_weight=color_weight)
            rec_feat = build_feature_points(rec_pts, rec_colors, color_weight=color_weight)

            # chamfer
            mean_ab, mean_ba, chamfer = chamfer_distance(gt_feat, rec_feat)
            # hausdorff
            max_ab, max_ba, hausdorff = hausdorff_distance(gt_feat, rec_feat)
            # precision/recall/fscore
            precision, recall, fscore, mean_rec_to_gt, mean_gt_to_rec = precision_recall_fscore(gt_feat, rec_feat, threshold=threshold)

            # derive short object name and 4-digit frame from basename
            base = os.path.splitext(os.path.basename(name))[0]
            # object name: text before first underscore
            obj_name = base.split('_')[0] if '_' in base else base
            # frame: last 4 digits in the basename
            m = re.search(r'(\d{4})$', base)
            frame = m.group(1) if m else ''

            row = {
                'name': obj_name,
                'frame': frame,
                'gt_path': gt_path,
                'rec_path': rec_path,
                'mean_d_gt_to_rec': float(mean_ab),
                'mean_d_rec_to_gt': float(mean_ba),
                'chamfer': float(chamfer),
                'max_d_gt_to_rec': float(max_ab),
                'max_d_rec_to_gt': float(max_ba),
                'hausdorff': float(hausdorff),
                'precision': float(precision),
                'recall': float(recall),
                'fscore': float(fscore),
                'mean_rec_to_gt': float(mean_rec_to_gt),
                'mean_gt_to_rec': float(mean_gt_to_rec),
            }
            writer.writerow(row)
            if verbose:
                print(f"  chamfer={chamfer:.6f}, hausdorff={hausdorff:.6f}, prec={precision:.4f}, rec={recall:.4f}, f={fscore:.4f}")

    if verbose:
        print(f"All done. Results saved to {out_csv}")


def parse_args():
    p = argparse.ArgumentParser(description='Compute point-cloud metrics between matched PLY files')
    p.add_argument('--gt_dir', required=True, help='Directory with ground-truth PLY files')
    p.add_argument('--rec_dir', required=True, help='Directory with reconstructed/low-quality PLY files')
    p.add_argument('--out_csv', default='results.csv', help='CSV file to write results')
    p.add_argument('--threshold', type=float, default=0.5, help='Distance threshold for precision/recall/fscore')
    p.add_argument('--color_weight', type=float, default=0.0, help='If >0, include color as extra dims scaled by this weight')
    p.add_argument('--append', action='store_true', help='Append results to out_csv instead of overwriting')
    p.add_argument('--no_verbose', action='store_true', help='Turn off verbose printing')
    p.add_argument('--max_points', type=int, default=0, help='If >0, randomly subsample each point cloud to at most this many points to speed up computation')
    return p.parse_args()


if __name__ == '__main__':
    args = parse_args()
    if not os.path.isdir(args.gt_dir):
        print(f"Error: gt_dir does not exist: {args.gt_dir}")
        sys.exit(1)
    if not os.path.isdir(args.rec_dir):
        print(f"Error: rec_dir does not exist: {args.rec_dir}")
        sys.exit(1)

    process_all(args.gt_dir, args.rec_dir, args.out_csv, threshold=args.threshold, color_weight=args.color_weight, verbose=not args.no_verbose, append=args.append, max_points=args.max_points)
